from typing import Protocol, List, Optional
import uuid
from ragaas.domain.entities.tenant import Tenant
from ragaas.domain.entities.namespace import Namespace
from ragaas.domain.entities.document import Document
from ragaas.domain.entities.api_key import APIKey
from ragaas.domain.entities.end_user import EndUser
from ragaas.domain.entities.chat_session import ChatSession
from ragaas.domain.entities.usage_event import UsageEvent

class ITenantRepository(Protocol):
    def get_by_id(self, tenant_id: uuid.UUID) -> Optional[Tenant]: ...
    def get_by_email(self, email: str) -> Optional[Tenant]: ...
    def save(self, tenant: Tenant) -> None: ...

class INamespaceRepository(Protocol):
    def get_by_id(self, namespace_id: uuid.UUID) -> Optional[Namespace]: ...
    def list_by_tenant(self, tenant_id: uuid.UUID) -> List[Namespace]: ...
    def save(self, namespace: Namespace) -> None: ...
    def delete(self, namespace_id: uuid.UUID) -> None: ...

class IDocumentRepository(Protocol):
    def get_by_id(self, document_id: uuid.UUID) -> Optional[Document]: ...
    def list_by_namespace(self, namespace_id: uuid.UUID) -> List[Document]: ...
    def save(self, document: Document) -> None: ...
    def delete(self, document_id: uuid.UUID) -> None: ...

class IAPIKeyRepository(Protocol):
    def get_by_hash(self, key_hash: str) -> Optional[APIKey]: ...
    def save(self, api_key: APIKey) -> None: ...

class IEndUserRepository(Protocol):
    def get_by_id(self, end_user_id: uuid.UUID) -> Optional[EndUser]: ...
    def get_by_external_id(self, tenant_id: uuid.UUID, external_id: str) -> Optional[EndUser]: ...
    def save(self, end_user: EndUser) -> None: ...

class IChatSessionRepository(Protocol):
    def get_by_id(self, session_id: uuid.UUID) -> Optional[ChatSession]: ...
    def list_by_end_user(self, end_user_id: uuid.UUID) -> List[ChatSession]: ...
    def save(self, session: ChatSession) -> None: ...

class IUsageEventRepository(Protocol):
    def save(self, event: UsageEvent) -> None: ...
