from typing import Protocol, List, Dict, Any, BinaryIO
import uuid
from ragaas.domain.entities.chunk import DocumentChunk
from ragaas.domain.value_objects import LLMConfig, EmbeddingConfig, LLMResponse, SourceReference

class ILLMService(Protocol):
    def generate_embedding(self, text: str, config: EmbeddingConfig) -> List[float]: ...
    def generate_answer(self, query: str, context: str, history: List[Dict[str, str]], config: LLMConfig) -> LLMResponse: ...

class IVectorStore(Protocol):
    def upsert_chunks(self, namespace_id: uuid.UUID, chunks: List[DocumentChunk]) -> None: ...
    def search_similar(self, namespace_id: uuid.UUID, query_embedding: List[float], top_k: int) -> List[SourceReference]: ...
    def delete_namespace_vectors(self, namespace_id: uuid.UUID) -> None: ...
    def delete_document_vectors(self, document_id: uuid.UUID) -> None: ...

class IBillingService(Protocol):
    def report_usage(self, tenant_id: uuid.UUID, tokens_used: int, event_type: str) -> None: ...

class IFileStorage(Protocol):
    def upload_file(self, file_obj: BinaryIO, path: str) -> str: ...
    def download_file(self, path: str) -> BinaryIO: ...
    def delete_file(self, path: str) -> None: ...

class IDocumentParser(Protocol):
    def extract_text(self, file_obj: BinaryIO, file_type: str) -> str: ...

class ITextChunker(Protocol):
    def chunk_text(self, text: str, chunk_size: int, chunk_overlap: int) -> List[str]: ...

class IBackgroundWorker(Protocol):
    def queue_document_ingestion(self, document_id: uuid.UUID) -> None: ...
