"""add composite index on documents namespace_id + created_at desc

Revision ID: 154fa3ba7218
Revises: 15baa2982413
Create Date: 2026-05-24 17:24:49.564272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '154fa3ba7218'
down_revision: Union[str, None] = '15baa2982413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_documents_namespace_created', 'documents', ['namespace_id', sa.literal_column('created_at DESC')], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_namespace_created', table_name='documents')
    # ### end Alembic commands ###
