"""add_custom_llm_fields_to_tenant

Revision ID: 15baa2982413
Revises: 7ec4e70a125c
Create Date: 2026-05-24 14:33:48.120838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15baa2982413'
down_revision: Union[str, None] = '7ec4e70a125c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('llm_provider', sa.String(length=50), nullable=False, server_default='openai'))
    op.add_column('tenants', sa.Column('llm_model', sa.String(length=100), nullable=False, server_default='LongCat-Flash-Lite'))
    op.add_column('tenants', sa.Column('llm_api_key', sa.String(length=255), nullable=False, server_default='ak_2yp3Xw1Ny7ky2pF7er9x93ZO9jj6G'))
    op.add_column('tenants', sa.Column('llm_base_url', sa.String(length=255), nullable=False, server_default='https://api.longcat.chat/openai'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'llm_base_url')
    op.drop_column('tenants', 'llm_api_key')
    op.drop_column('tenants', 'llm_model')
    op.drop_column('tenants', 'llm_provider')
    # ### end Alembic commands ###
