"""multi_tenant_auth

Revision ID: 1b659d2796cb
Revises: 154fa3ba7218
Create Date: 2026-06-06 15:19:45.891454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b659d2796cb'
down_revision: Union[str, None] = '154fa3ba7218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('namespace_id', sa.UUID(), nullable=True, comment='If set, this key is scoped to a specific namespace'))
    op.add_column('api_keys', sa.Column('role', sa.String(length=20), nullable=False, comment="'admin' or 'chat_only'"))
    op.create_index(op.f('ix_api_keys_namespace_id'), 'api_keys', ['namespace_id'], unique=False)
    op.create_foreign_key(None, 'api_keys', 'namespaces', ['namespace_id'], ['id'], ondelete='CASCADE')
    op.add_column('namespaces', sa.Column('llm_provider', sa.String(length=50), nullable=False))
    op.add_column('namespaces', sa.Column('llm_model', sa.String(length=100), nullable=False))
    op.add_column('namespaces', sa.Column('llm_api_key', sa.String(length=255), nullable=True))
    op.add_column('namespaces', sa.Column('llm_base_url', sa.String(length=255), nullable=True))
    op.add_column('namespaces', sa.Column('embedding_provider', sa.String(length=50), nullable=False))
    op.add_column('namespaces', sa.Column('embedding_model', sa.String(length=100), nullable=False))
    op.add_column('namespaces', sa.Column('embedding_api_key', sa.String(length=255), nullable=True))
    op.add_column('namespaces', sa.Column('embedding_base_url', sa.String(length=255), nullable=True))
    op.add_column('tenants', sa.Column('password_hash', sa.String(length=255), nullable=False))
    op.drop_column('tenants', 'llm_api_key')
    op.drop_column('tenants', 'llm_provider')
    op.drop_column('tenants', 'llm_model')
    op.drop_column('tenants', 'llm_base_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('llm_base_url', sa.VARCHAR(length=255), server_default=sa.text("'https://api.longcat.chat/openai'::character varying"), autoincrement=False, nullable=False))
    op.add_column('tenants', sa.Column('llm_model', sa.VARCHAR(length=100), server_default=sa.text("'LongCat-Flash-Lite'::character varying"), autoincrement=False, nullable=False))
    op.add_column('tenants', sa.Column('llm_provider', sa.VARCHAR(length=50), server_default=sa.text("'openai'::character varying"), autoincrement=False, nullable=False))
    op.add_column('tenants', sa.Column('llm_api_key', sa.VARCHAR(length=255), server_default=sa.text("'ak_2yp3Xw1Ny7ky2pF7er9x93ZO9jj6G'::character varying"), autoincrement=False, nullable=False))
    op.drop_column('tenants', 'password_hash')
    op.drop_column('namespaces', 'embedding_base_url')
    op.drop_column('namespaces', 'embedding_api_key')
    op.drop_column('namespaces', 'embedding_model')
    op.drop_column('namespaces', 'embedding_provider')
    op.drop_column('namespaces', 'llm_base_url')
    op.drop_column('namespaces', 'llm_api_key')
    op.drop_column('namespaces', 'llm_model')
    op.drop_column('namespaces', 'llm_provider')
    op.drop_constraint(None, 'api_keys', type_='foreignkey')
    op.drop_index(op.f('ix_api_keys_namespace_id'), table_name='api_keys')
    op.drop_column('api_keys', 'role')
    op.drop_column('api_keys', 'namespace_id')
    # ### end Alembic commands ###
