# Generated by Django 6.0.6 on 2026-06-09 09:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.EmailField(db_index=True, max_length=320, unique=True)),
                ('plan', models.CharField(choices=[('starter', 'Starter'), ('growth', 'Growth'), ('scale', 'Scale'), ('enterprise', 'Enterprise')], default='starter', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Namespace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=64)),
                ('doc_count', models.IntegerField(default=0)),
                ('token_count', models.BigIntegerField(default=0)),
                ('llm_provider', models.CharField(default='openai', max_length=50)),
                ('llm_model', models.CharField(default='gpt-4o-mini', max_length=100)),
                ('llm_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('llm_base_url', models.CharField(blank=True, max_length=255, null=True)),
                ('embedding_provider', models.CharField(default='dashscope', max_length=50)),
                ('embedding_model', models.CharField(default='text-embedding-v4', max_length=100)),
                ('embedding_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('embedding_base_url', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='namespaces', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('tenant', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key_hash', models.TextField(unique=True)),
                ('prefix', models.CharField(db_index=True, max_length=50)),
                ('label', models.CharField(blank=True, max_length=100, null=True)),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('role', models.CharField(default='admin', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
                ('namespace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ragaas.namespace')),
            ],
        ),
        migrations.CreateModel(
            name='UsageEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('query', 'Query'), ('ingest', 'Ingest')], db_index=True, max_length=20)),
                ('tokens_used', models.IntegerField(default=0)),
                ('query_ms', models.IntegerField(blank=True, null=True)),
                ('model_used', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_events', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('txt', 'TXT'), ('json', 'JSON'), ('xml', 'XML'), ('csv', 'CSV'), ('html', 'HTML'), ('md', 'MD'), ('pptx', 'PPTX')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed')], db_index=True, default='pending', max_length=20)),
                ('chunk_count', models.IntegerField(default=0)),
                ('images_inside', models.BooleanField(default=False)),
                ('s3_key', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('namespace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='ragaas.namespace')),
            ],
            options={
                'indexes': [models.Index(fields=['namespace', '-created_at'], name='ragaas_docu_namespa_b04d00_idx')],
            },
        ),
    ]
