# Generated by Django 6.0.6 on 2026-06-09 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragaas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='llm_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='llm_base_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='llm_model',
            field=models.CharField(default='gpt-4o-mini', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='llm_provider',
            field=models.CharField(default='openai', max_length=50),
        ),
    ]
