# Generated by Django 6.0.6 on 2026-06-09 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragaas', '0002_tenant_llm_api_key_tenant_llm_base_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='namespace',
            name='config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='namespace',
            name='rag_type',
            field=models.CharField(default='standard', max_length=20),
        ),
    ]
