# Generated by Django 6.0.6 on 2026-06-10 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragaas', '0003_namespace_config_namespace_rag_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='allowed_rag_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tenant',
            name='allowed_vector_dbs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tenant',
            name='billing_cycle_reset',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='can_deploy_api',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenant',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('start', 'Start'), ('mid', 'Mid'), ('prime', 'Prime'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
    ]
