# Generated by Django 6.0.6 on 2026-06-10 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ragaas', '0004_tenant_allowed_rag_types_tenant_allowed_vector_dbs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='embedding_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='embedding_base_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='tenant',
            name='embedding_model',
            field=models.CharField(default='all-MiniLM-L6-v2', max_length=100),
        ),
        migrations.AddField(
            model_name='tenant',
            name='embedding_provider',
            field=models.CharField(default='local', max_length=50),
        ),
    ]
